#include <QCoreApplication>
#include <QtCore>
#include <QDebug>
#include <QString>
#include <QObject> 
#include <QFontMetrics> 
#include <QFont> 

QString createAss()
{
    QString qs = "[Script Info]\r\n"
"; Script generated by FFmpeg/Lavc57.24.102\n"
"ScriptType: v4.00+\n"
"PlayResX: 384\n"
"PlayResY: 288\n"
"\n"
"[V4+ Styles]\n"
"Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n"
"Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,0\n"
"\n"
"[Events]\n"
"Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
"Dialogue: 0,0:00:00.01,0:00:00.94,Default,,0,0,0,,{\\move(0,0,60,120 [,100,500])}{\\fad(400,80)}{\\fs18\\t(130,500,\\fry360)}- Oh, stupid.\n"
"Dialogue: 0,0:00:01.01,0:00:01.99,Default,,0,0,0,,Go kill something.";
    qDebug(qs.toLatin1());
    return qs;
}
#if 0
class Task : public QObject
{
    Q_OBJECT
public:
    Task(QObject *parent = 0) : QObject(parent) {}

public slots:
    void run()
    {
        // Do processing here
        QString b = A();
		qDebug() << "1 b: " << b;
        change();
		qDebug() << "2 b: " << b;
		qDebug() << "qs: " << createAss();
        emit finished();
    }
private:
    QString a;
    QString A(){
        a = "aaaaaaaaa";
        return a;
    }
    void change(){
        a = "bbbbbb";
    }
signals:
    void finished();
};
#include "main.moc"
#endif

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    QFont font;
    font.setPointSize(8); 
    QFontMetrics fm(font); 
    int fw = fm.width("test");
    int fh;// = fm.height();
    qDebug() << "fw: " << fw <<" fh: " << fh ;
#if 0
	// Task parented to the application so that it
    // will be deleted by the application.
    Task *task = new Task(&a);

    // This will cause the application to exit when
    // the task signals finished.    
    QObject::connect(task, SIGNAL(finished()), &a, SLOT(quit()));

    // This will run the task from the application event loop.
    QTimer::singleShot(0, task, SLOT(run()));

#endif

#if 0
    int m_iStartTime = 1212;
    int m_iStartPoint = 0;
    int m_iEntPoint = 31233;
    int m_duration = 5000;
    int iRealLength = m_iEntPoint - m_iStartPoint+m_iStartTime;
    QString test = QString("[1:a]atrim=0:%1,asetpts=PTS-STARTPTS[aud1];"
                    "[2:a]atrim=%2:%3,asetpts=PTS-STARTPTS[aud2];"
                    "[aud1][aud2]concat=n=2:v=0:a=1[aout]").
            arg(QString::number((float)m_iStartTime/1000, 'f',2)).
            arg((float)m_iStartPoint/1000).
            arg(iRealLength<=m_duration?((float)m_iEntPoint/1000):((float)(m_duration-m_iStartTime+m_iStartPoint)/1000));
    qDebug() << test;
#endif 

    return a.exec();
}
